### ISSUE TITLE
Problems with Umlauts when uploading data with node.js

### ISSUE THREAD

**Issue by TheFive** [plotly/plotly-nodejs#15] opened 2015-01-18 09:44 UTC
If i plot a graph with ä ö ü or ß  in the name of the scatter i get the following error message:

{"body":{"url":"","message":"","warning":"","filename":"","error":"origin not 'plot', 'layout', or 'style'"},"statusCode":200}

I am using your plot.ly samples for node.js (just uploading several traces). Replacing the Umlauts by
ue, oe, ae, ss fixes the problem.

Christoph

**Comment by alexander-daniel** [comment] 2015-01-20 20:39
Thanks for pointing this out. I'll take a look into special chars!

**Comment by KenanY** [comment] 2015-01-26 13:09
I'm also running into the issue. My temporary solution is to of course strip characters like `Ü` and `ü`.

**Comment by alexander-daniel** [comment] 2015-01-28 22:18
Alright, looks like an issue on our backend with parsing the special chars. The node API handles it just fine.. I'll report back to this issue when it is fixed on our severs! 
@KenanY @TheFive

**Comment by TheFive** [comment] 2015-01-28 22:19
Thanks for the update. I am a little bit curious: What language are you using on "your servers" ?.

Christoph

**Comment by alexander-daniel** [comment] 2015-01-28 22:25
The REST server is Python/Django
The streaming server is written in node.js

The problem is at the REST server, as each streaming graph requires a graph be initialized, and the REST server request is failing with the special chars. These aren't even making it to the streaming server.

We've got a fix in the pipe, shouldn't be too long!

**Comment by TheFive** [comment] 2015-05-01 10:15
Hi @alexander-daniel 

where you able to fix the issue ?

Christoph

**Comment by TheFive** [comment] 2015-05-24 14:16
Hi Plotly,

is it so hard to implement a modern "utf8" compatible Web Application in 2015 for the world outside the US ? ( :-) )

Sorry, i have tested it, and i have still to exchange ü,ä,ö by ue, ae, ou.

i have tested to substitute these values by &uuml; &auml; &ouml; but it does not help.

Christoph

**Comment by alexander-daniel** [comment] 2015-10-26 14:55
@TheFive Should be resolved now, thank you for your patience.

**Closed** 2015-10-26 14:55 UTC
